### ISSUE TITLE
use sudo `sudo: unable to send audit message: Operation not permitted`

### ISSUE THREAD

**Issue by wc7086** [linuxserver/docker-code-server#100]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

Do not appear `sudo: unable to send audit message: Operation not permitted`
Both docker and podman have this problem running this image.
## Current Behavior

When using sudo, it will prompt `sudo: unable to send audit message: Operation not permitted`
## Steps to Reproduce

1. run the container
2. open web or `exec -it` join container
3. use `sudo apt update` or use `sudo` to execute any other command
4. `sudo: unable to send audit message: Operation not permitted` appears in the console

## Environment
**OS:** Debian11
**CPU architecture:** x86_64
**How docker service was installed:** `curl -fsSL https://get.docker.com -o get-docker.sh && sh get-docker.sh`

## Command used to create docker container (run/create/compose/screenshot)

```
mkdir -p ~/docker/coder && chown -R 1000:1000 ~/docker/coder && docker run -d --name=code-server -e PUID=1000 -e PGID=1000 -e TZ=Asia/Shanghai -e PASSWORD=test -e SUDO_PASSWORD=test -e DEFAULT_WORKSPACE=/config/workspace -p 15983:8443 -v ~/docker/coder:/config --restart unless-stopped linuxserver/code-server
```
## Docker logs

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing... 
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 01-migrations: executing... 
[migrations] started
[migrations] no migrations found
[cont-init.d] 01-migrations: exited 0.
[cont-init.d] 02-tamper-check: executing... 
**** Potential tampering with custom scripts/services detected ****
**** Folder /config/custom-cont-init.d is moved to /config/custom-cont-init.d.OzUXFpId ****
**** Folder /config/custom-services.d is moved to /config/custom-services.d.OzUXFpId ****
**** The folders '/config/custom-cont-init.d' and '/config/custom-services.d'; and their contents need to all be owned by root to prevent root escalation inside the container!!! ****
[cont-init.d] 02-tamper-check: exited 0.
[cont-init.d] 10-adduser: executing... 

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing... 
setting up sudo access
adding abc to sudoers
setting sudo password using SUDO_PASSWORD env var
New password: Retype new password: passwd: password updated successfully
setting permissions::configuration
setting permissions::workspace
[cont-init.d] 30-config: exited 0.
[cont-init.d] 90-custom-folders: executing... 
[cont-init.d] 90-custom-folders: exited 0.
[cont-init.d] 99-custom-scripts: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[2022-01-29T06:23:58.460Z] info  code-server 4.0.2 5cdfe74686aa73e023f8354a9a6014eb30caa7dd
[2022-01-29T06:23:58.463Z] info  Using user-data-dir ~/data
[2022-01-29T06:23:58.471Z] info  Using config file ~/.config/code-server/config.yaml
[2022-01-29T06:23:58.471Z] info  HTTP server listening on http://0.0.0.0:8443/ 
[2022-01-29T06:23:58.471Z] info    - Authentication is enabled
[2022-01-29T06:23:58.471Z] info      - Using password from $PASSWORD
[2022-01-29T06:23:58.471Z] info    - Not serving HTTPS 
[14:24:03] Extension host agent started.
[14:24:11] [10.88.0.1][43c9e70f][ManagementConnection] New connection established.
[14:24:12] [10.88.0.1][c1fb8ef4][ExtensionHostConnection] New connection established.
[14:24:12] [10.88.0.1][c1fb8ef4][ExtensionHostConnection] <423> Launched Extension Host Process.
Error: Unexpected SIGPIPE
    at process.<anonymous> (/usr/local/share/.config/yarn/global/node_modules/code-server/vendor/modules/code-oss-dev/out/bootstrap.js:1:370)
    at process.emit (events.js:400:28)
Error: Unexpected SIGPIPE
    at process.<anonymous> (/usr/local/share/.config/yarn/global/node_modules/code-server/vendor/modules/code-oss-dev/out/bootstrap.js:1:370)
    at process.emit (events.js:400:28)
[14:27:30] [10.88.0.1][6b9f7175][ManagementConnection] New connection established.
[14:27:31] RequestStore#acceptReply was called without receiving a matching request 26
[14:27:31] RequestStore#acceptReply was called without receiving a matching request 27
[14:27:32] RequestStore#acceptReply was called without receiving a matching request 28
[14:27:33] RequestStore#acceptReply was called without receiving a matching request 29
[14:27:33] RequestStore#acceptReply was called without receiving a matching request 30
[14:27:33] RequestStore#acceptReply was called without receiving a matching request 31
[14:27:33] RequestStore#acceptReply was called without receiving a matching request 32
[14:27:33] [10.88.0.1][35ebae9b][ExtensionHostConnection] New connection established.
[14:27:33] [10.88.0.1][35ebae9b][ExtensionHostConnection] <886> Launched Extension Host Process.
[14:27:33] RequestStore#acceptReply was called without receiving a matching request 33
[14:27:33] RequestStore#acceptReply was called without receiving a matching request 34
[14:27:34] RequestStore#acceptReply was called without receiving a matching request 35
Error: Unexpected SIGPIPE
    at process.<anonymous> (/usr/local/share/.config/yarn/global/node_modules/code-server/vendor/modules/code-oss-dev/out/bootstrap.js:1:370)
    at process.emit (events.js:400:28)
[14:27:35] RequestStore#acceptReply was called without receiving a matching request 36
[14:27:35] RequestStore#acceptReply was called without receiving a matching request 37
[14:27:35] RequestStore#acceptReply was called without receiving a matching request 38
[14:27:35] RequestStore#acceptReply was called without receiving a matching request 39
[14:27:35] RequestStore#acceptReply was called without receiving a matching request 40
Error: Unexpected SIGPIPE
    at process.<anonymous> (/usr/local/share/.config/yarn/global/node_modules/code-server/vendor/modules/code-oss-dev/out/bootstrap.js:1:370)
    at process.emit (events.js:400:28)
```

**Comment by aptalca** [comment]
sudo works just fine in terminal in code-server gui. When you exec in, you're already root unless you exec in as a specific user

**Comment by markstos** [comment]
The container lacks the capability for "audit writes". 

This issue could be-opened and the docs or related container code could be updated to reflect that this capability is needed for these audit writes to work.

Ref: https://github.com/pi-hole/docker-pi-hole/issues/1007#issuecomment-1053208134
