### ISSUE TITLE
"HTML Language Features" error，not work

### ISSUE THREAD

**Issue by mimokini** [linuxserver/docker-code-server#107]
## Expected Behavior
"HTML Language Features" error，not work

## Current Behavior
The HTML Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted.

## Steps to Reproduce
1.Open the browser
2.New HTML

## Environment
**OS:**
**CPU architecture:** x86_64/arm32/arm64
**How docker service was installed:**
System：Unraid 6.9.2
cpu：J4125 x86_64
docker：20.10.5

## Command used to create docker container (run/create/compose/screenshot)
Install in the Community Applications.
The "lscr.io/linuxserver/code-server" " is installed by default.

## VS logs
internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module 'typescript'
Require stack:
- /app/code-server/lib/vscode/extensions/html-language-features/server/dist/node/htmlServerMain.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.5034 (/app/code-server/lib/vscode/extensions/html-language-features/server/dist/node/htmlServerMain.js:1:1335953)
    at n (/app/code-server/lib/vscode/extensions/html-language-features/server/dist/node/htmlServerMain.js:1:1336145)
    at Object.5906 (/app/code-server/lib/vscode/extensions/html-language-features/server/dist/node/htmlServerMain.js:1:1310082)
    at n (/app/code-server/lib/vscode/extensions/html-language-features/server/dist/node/htmlServerMain.js:1:1336145)
    at Object.5704 (/app/code-server/lib/vscode/extensions/html-language-features/server/dist/node/htmlServerMain.js:1:1323446)
    at n (/app/code-server/lib/vscode/extensions/html-language-features/server/dist/node/htmlServerMain.js:1:1336145) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/app/code-server/lib/vscode/extensions/html-language-features/server/dist/node/htmlServerMain.js'
  ]
}
[Info  - 11:24:47 AM] Connection to server got closed. Server will restart.
internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module 'typescript'
Require stack:
- /app/code-server/lib/vscode/extensions/html-language-features/server/dist/node/htmlServerMain.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.5034 (/app/code-server/lib/vscode/extensions/html-language-features/server/dist/node/htmlServerMain.js:1:1335953)
    at n (/app/code-server/lib/vscode/extensions/html-language-features/server/dist/node/htmlServerMain.js:1:1336145)
    at Object.5906 (/app/code-server/lib/vscode/extensions/html-language-features/server/dist/node/htmlServerMain.js:1:1310082)
    at n (/app/code-server/lib/vscode/extensions/html-language-features/server/dist/node/htmlServerMain.js:1:1336145)
    at Object.5704 (/app/code-server/lib/vscode/extensions/html-language-features/server/dist/node/htmlServerMain.js:1:1323446)
    at n (/app/code-server/lib/vscode/extensions/html-language-features/server/dist/node/htmlServerMain.js:1:1336145) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/app/code-server/lib/vscode/extensions/html-language-features/server/dist/node/htmlServerMain.js'
  ]
}
[Info  - 11:24:47 AM] Connection to server got closed. Server will restart.
internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module 'typescript'
Require stack:
- /app/code-server/lib/vscode/extensions/html-language-features/server/dist/node/htmlServerMain.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.5034 (/app/code-server/lib/vscode/extensions/html-language-features/server/dist/node/htmlServerMain.js:1:1335953)
    at n (/app/code-server/lib/vscode/extensions/html-language-features/server/dist/node/htmlServerMain.js:1:1336145)
    at Object.5906 (/app/code-server/lib/vscode/extensions/html-language-features/server/dist/node/htmlServerMain.js:1:1310082)
    at n (/app/code-server/lib/vscode/extensions/html-language-features/server/dist/node/htmlServerMain.js:1:1336145)
    at Object.5704 (/app/code-server/lib/vscode/extensions/html-language-features/server/dist/node/htmlServerMain.js:1:1323446)
    at n (/app/code-server/lib/vscode/extensions/html-language-features/server/dist/node/htmlServerMain.js:1:1336145) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/app/code-server/lib/vscode/extensions/html-language-features/server/dist/node/htmlServerMain.js'
  ]
}
[Info  - 11:24:47 AM] Connection to server got closed. Server will restart.
internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module 'typescript'
Require stack:
- /app/code-server/lib/vscode/extensions/html-language-features/server/dist/node/htmlServerMain.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.5034 (/app/code-server/lib/vscode/extensions/html-language-features/server/dist/node/htmlServerMain.js:1:1335953)
    at n (/app/code-server/lib/vscode/extensions/html-language-features/server/dist/node/htmlServerMain.js:1:1336145)
    at Object.5906 (/app/code-server/lib/vscode/extensions/html-language-features/server/dist/node/htmlServerMain.js:1:1310082)
    at n (/app/code-server/lib/vscode/extensions/html-language-features/server/dist/node/htmlServerMain.js:1:1336145)
    at Object.5704 (/app/code-server/lib/vscode/extensions/html-language-features/server/dist/node/htmlServerMain.js:1:1323446)
    at n (/app/code-server/lib/vscode/extensions/html-language-features/server/dist/node/htmlServerMain.js:1:1336145) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/app/code-server/lib/vscode/extensions/html-language-features/server/dist/node/htmlServerMain.js'
  ]
}
[Info  - 11:24:47 AM] Connection to server got closed. Server will restart.
internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module 'typescript'
Require stack:
- /app/code-server/lib/vscode/extensions/html-language-features/server/dist/node/htmlServerMain.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.5034 (/app/code-server/lib/vscode/extensions/html-language-features/server/dist/node/htmlServerMain.js:1:1335953)
    at n (/app/code-server/lib/vscode/extensions/html-language-features/server/dist/node/htmlServerMain.js:1:1336145)
    at Object.5906 (/app/code-server/lib/vscode/extensions/html-language-features/server/dist/node/htmlServerMain.js:1:1310082)
    at n (/app/code-server/lib/vscode/extensions/html-language-features/server/dist/node/htmlServerMain.js:1:1336145)
    at Object.5704 (/app/code-server/lib/vscode/extensions/html-language-features/server/dist/node/htmlServerMain.js:1:1323446)
    at n (/app/code-server/lib/vscode/extensions/html-language-features/server/dist/node/htmlServerMain.js:1:1336145) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/app/code-server/lib/vscode/extensions/html-language-features/server/dist/node/htmlServerMain.js'
  ]
}
[Error - 11:24:48 AM] Connection to server got closed. Server will not be restarted.

**Comment by aptalca** [comment]
That looks like an upstream issue. Now that we are using their precompiled tarballs, it should be reported to them.
