### ISSUE TITLE
Cannot open terminal with code-server version 4.4.0 

### ISSUE THREAD

**Issue by namnhcntt** [linuxserver/docker-code-server#110]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

Can open terminal and excecute script

## Current Behavior

Cannot open terminal. Error in image:
![image](https://user-images.githubusercontent.com/4961896/168258672-0ff7e650-2db4-42a3-8971-072f0fb1464a.png)

## Steps to Reproduce

1. Install code-server by docker swarm service
```
namnh:
    image: lscr.io/linuxserver/code-server:latest
    user: "0:0"
    environment:
      - TZ=Asia/Ho_Chi_Minh
      - PASSWORD=<<my password>>
      - SUDO_PASSWORD=<<my password>> 
    volumes:
      - config:/config # source code sẽ đặt ở /config/workspace
```
2. Open code server in browser
4. Open terminal
5. Get the error

## Environment
**OS:** Docker swarm in Centos 7
**CPU architecture:** x86_64
**How docker service was installed:**

Script in step 1 below.

## Command used to create docker container (run/create/compose/screenshot)

Script in step 1 below.
## Docker logs

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing... 
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 01-migrations: executing... 
[migrations] started
[migrations] no migrations found
[cont-init.d] 01-migrations: exited 0.
[cont-init.d] 02-tamper-check: executing... 
[cont-init.d] 02-tamper-check: exited 0.
[cont-init.d] 10-adduser: executing... 
usermod: no changes
-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/
Brought to you by linuxserver.io
-------------------------------------
To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------
User uid:    911
User gid:    911
-------------------------------------
[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing... 
setting up sudo access
adding abc to sudoers
setting sudo password using SUDO_PASSWORD env var
New password: Retype new password: passwd: password updated successfully
setting permissions::configuration
setting permissions::workspace
[cont-init.d] 30-config: exited 0.
[cont-init.d] 90-custom-folders: executing... 
[cont-init.d] 90-custom-folders: exited 0.
[cont-init.d] 99-custom-scripts: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[2022-05-13T09:38:49.990Z] info  Wrote default config file to ~/.config/code-server/config.yaml
[2022-05-13T09:38:50.381Z] info  code-server 4.4.0 b088ec7adf9e17bc75215f79e21498eb40da03ed
[2022-05-13T09:38:50.382Z] info  Using user-data-dir ~/data
[2022-05-13T09:38:50.392Z] info  Using config file ~/.config/code-server/config.yaml
[2022-05-13T09:38:50.392Z] info  HTTP server listening on http://0.0.0.0:8443/ 
[2022-05-13T09:38:50.392Z] info    - Authentication is enabled
[2022-05-13T09:38:50.392Z] info      - Using password from $PASSWORD
[2022-05-13T09:38:50.392Z] info    - Not serving HTTPS 
[16:38:59] Extension host agent started.
[16:38:59] [10.0.4.209][9f02653a][ManagementConnection] Unknown reconnection token (never seen).
[16:38:59] [10.0.4.209][c88b9145][ExtensionHostConnection] Unknown reconnection token (never seen).
[16:39:01] [10.0.4.209][f662f03b][ManagementConnection] New connection established.
[16:39:02] [10.0.4.209][9cc4e8e9][ExtensionHostConnection] New connection established.
[16:39:02] [10.0.4.209][9cc4e8e9][ExtensionHostConnection] <389> Launched Extension Host Process.
[16:39:02] [File Watcher (parcel)] correcting a path to watch that seems to be a symbolic link or wrong casing (original: /config/workspace/, real: /config/workspace)
rejected promise not handled within 1 second: TypeError: Cannot read properties of undefined (reading 'windowsEnableConpty')
stack trace: TypeError: Cannot read properties of undefined (reading 'windowsEnableConpty'),    at new Ae (/app/code-server/lib/vscode/out/vs/platform/terminal/node/ptyHostMain.js:17:10692),    at C.createProcess (/app/code-server/lib/vscode/out/vs/platform/terminal/node/ptyHostMain.js:20:533),    at Object.call (/app/code-server/lib/vscode/out/vs/platform/terminal/node/ptyHostMain.js:13:8332),    at S.onPromise (/app/code-server/lib/vscode/out/vs/platform/terminal/node/ptyHostMain.js:12:4867),    at S.onRawMessage (/app/code-server/lib/vscode/out/vs/platform/terminal/node/ptyHostMain.js:12:4262),    at /app/code-server/lib/vscode/out/vs/platform/terminal/node/ptyHostMain.js:12:3554,    at L.invoke (/app/code-server/lib/vscode/out/vs/platform/terminal/node/ptyHostMain.js:8:145),    at l.fire (/app/code-server/lib/vscode/out/vs/platform/terminal/node/ptyHostMain.js:8:1856),    at process.U (/app/code-server/lib/vscode/out/vs/platform/terminal/node/ptyHostMain.js:6:34934),    at process.emit (node:events:527:28),    at emit (node:internal/child_process:938:14),    at processTicksAndRejections (node:internal/process/task_queues:84:21)
[16:39:14] [Error [TypeError]: Cannot read properties of undefined (reading 'windowsEnableConpty'),    at new Ae (/app/code-server/lib/vscode/out/vs/platform/terminal/node/ptyHostMain.js:17:10692),    at C.createProcess (/app/code-server/lib/vscode/out/vs/platform/terminal/node/ptyHostMain.js:20:533),    at Object.call (/app/code-server/lib/vscode/out/vs/platform/terminal/node/ptyHostMain.js:13:8332),    at S.onPromise (/app/code-server/lib/vscode/out/vs/platform/terminal/node/ptyHostMain.js:12:4867),    at S.onRawMessage (/app/code-server/lib/vscode/out/vs/platform/terminal/node/ptyHostMain.js:12:4262),    at /app/code-server/lib/vscode/out/vs/platform/terminal/node/ptyHostMain.js:12:3554,    at L.invoke (/app/code-server/lib/vscode/out/vs/platform/terminal/node/ptyHostMain.js:8:145),    at l.fire (/app/code-server/lib/vscode/out/vs/platform/terminal/node/ptyHostMain.js:8:1856),    at process.U (/app/code-server/lib/vscode/out/vs/platform/terminal/node/ptyHostMain.js:6:34934),    at process.emit (node:events:527:28),    at emit (node:internal/child_process:938:14),    at processTicksAndRejections (node:internal/process/task_queues:84:21)]
[16:39:18] No ptyHost response to createProcess after 5 seconds
[16:41:21] [10.0.4.209][9cc4e8e9][ExtensionHostConnection] The client has reconnected.
[16:43:04] [10.0.4.209][9cc4e8e9][ExtensionHostConnection] The client has reconnected.
[16:44:47] [10.0.4.209][9cc4e8e9][ExtensionHostConnection] The client has reconnected.
[16:46:30] [10.0.4.209][9cc4e8e9][ExtensionHostConnection] The client has reconnected.
[16:48:14] [10.0.4.209][9cc4e8e9][ExtensionHostConnection] The client has reconnected.
rejected promise not handled within 1 second: TypeError: Cannot read properties of undefined (reading 'windowsEnableConpty')
stack trace: TypeError: Cannot read properties of undefined (reading 'windowsEnableConpty'),    at new Ae (/app/code-server/lib/vscode/out/vs/platform/terminal/node/ptyHostMain.js:17:10692),    at C.createProcess (/app/code-server/lib/vscode/out/vs/platform/terminal/node/ptyHostMain.js:20:533),    at Object.call (/app/code-server/lib/vscode/out/vs/platform/terminal/node/ptyHostMain.js:13:8332),    at S.onPromise (/app/code-server/lib/vscode/out/vs/platform/terminal/node/ptyHostMain.js:12:4867),    at S.onRawMessage (/app/code-server/lib/vscode/out/vs/platform/terminal/node/ptyHostMain.js:12:4262),    at /app/code-server/lib/vscode/out/vs/platform/terminal/node/ptyHostMain.js:12:3554,    at L.invoke (/app/code-server/lib/vscode/out/vs/platform/terminal/node/ptyHostMain.js:8:145),    at l.fire (/app/code-server/lib/vscode/out/vs/platform/terminal/node/ptyHostMain.js:8:1856),    at process.U (/app/code-server/lib/vscode/out/vs/platform/terminal/node/ptyHostMain.js:6:34934),    at process.emit (node:events:527:28),    at emit (node:internal/child_process:938:14),    at processTicksAndRejections (node:internal/process/task_queues:84:21)
[16:48:46] [Error [TypeError]: Cannot read properties of undefined (reading 'windowsEnableConpty'),    at new Ae (/app/code-server/lib/vscode/out/vs/platform/terminal/node/ptyHostMain.js:17:10692),    at C.createProcess (/app/code-server/lib/vscode/out/vs/platform/terminal/node/ptyHostMain.js:20:533),    at Object.call (/app/code-server/lib/vscode/out/vs/platform/terminal/node/ptyHostMain.js:13:8332),    at S.onPromise (/app/code-server/lib/vscode/out/vs/platform/terminal/node/ptyHostMain.js:12:4867),    at S.onRawMessage (/app/code-server/lib/vscode/out/vs/platform/terminal/node/ptyHostMain.js:12:4262),    at /app/code-server/lib/vscode/out/vs/platform/terminal/node/ptyHostMain.js:12:3554,    at L.invoke (/app/code-server/lib/vscode/out/vs/platform/terminal/node/ptyHostMain.js:8:145),    at l.fire (/app/code-server/lib/vscode/out/vs/platform/terminal/node/ptyHostMain.js:8:1856),    at process.U (/app/code-server/lib/vscode/out/vs/platform/terminal/node/ptyHostMain.js:6:34934),    at process.emit (node:events:527:28),    at emit (node:internal/child_process:938:14),    at processTicksAndRejections (node:internal/process/task_queues:84:21)]
[16:48:50] No ptyHost response to createProcess after 5 seconds
rejected promise not handled within 1 second: TypeError: Cannot read properties of undefined (reading 'windowsEnableConpty')
stack trace: TypeError: Cannot read properties of undefined (reading 'windowsEnableConpty'),    at new Ae (/app/code-server/lib/vscode/out/vs/platform/terminal/node/ptyHostMain.js:17:10692),    at C.createProcess (/app/code-server/lib/vscode/out/vs/platform/terminal/node/ptyHostMain.js:20:533),    at Object.call (/app/code-server/lib/vscode/out/vs/platform/terminal/node/ptyHostMain.js:13:8332),    at S.onPromise (/app/code-server/lib/vscode/out/vs/platform/terminal/node/ptyHostMain.js:12:4867),    at S.onRawMessage (/app/code-server/lib/vscode/out/vs/platform/terminal/node/ptyHostMain.js:12:4262),    at /app/code-server/lib/vscode/out/vs/platform/terminal/node/ptyHostMain.js:12:3554,    at L.invoke (/app/code-server/lib/vscode/out/vs/platform/terminal/node/ptyHostMain.js:8:145),    at l.fire (/app/code-server/lib/vscode/out/vs/platform/terminal/node/ptyHostMain.js:8:1856),    at process.U (/app/code-server/lib/vscode/out/vs/platform/terminal/node/ptyHostMain.js:6:34934),    at process.emit (node:events:527:28),    at emit (node:internal/child_process:938:14),    at processTicksAndRejections (node:internal/process/task_queues:84:21)
[16:50:01] [Error [TypeError]: Cannot read properties of undefined (reading 'windowsEnableConpty'),    at new Ae (/app/code-server/lib/vscode/out/vs/platform/terminal/node/ptyHostMain.js:17:10692),    at C.createProcess (/app/code-server/lib/vscode/out/vs/platform/terminal/node/ptyHostMain.js:20:533),    at Object.call (/app/code-server/lib/vscode/out/vs/platform/terminal/node/ptyHostMain.js:13:8332),    at S.onPromise (/app/code-server/lib/vscode/out/vs/platform/terminal/node/ptyHostMain.js:12:4867),    at S.onRawMessage (/app/code-server/lib/vscode/out/vs/platform/terminal/node/ptyHostMain.js:12:4262),    at /app/code-server/lib/vscode/out/vs/platform/terminal/node/ptyHostMain.js:12:3554,    at L.invoke (/app/code-server/lib/vscode/out/vs/platform/terminal/node/ptyHostMain.js:8:145),    at l.fire (/app/code-server/lib/vscode/out/vs/platform/terminal/node/ptyHostMain.js:8:1856),    at process.U (/app/code-server/lib/vscode/out/vs/platform/terminal/node/ptyHostMain.js:6:34934),    at process.emit (node:events:527:28),    at emit (node:internal/child_process:938:14),    at processTicksAndRejections (node:internal/process/task_queues:84:21)]
[16:50:05] No ptyHost response to createProcess after 5 seconds
[16:52:34] [10.0.4.209][9cc4e8e9][ExtensionHostConnection] The client has reconnected.
```

**Comment by Roxedus** [comment]
This is probably a app issue that needs to be reported upstream.
