### ISSUE TITLE
[BUG] Error: websocket close with status 1006

### ISSUE THREAD

**Issue by Herbs851** [linuxserver/docker-code-server#145]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Impossible to load workspace : 

![image](https://user-images.githubusercontent.com/51154851/223566649-40631293-002b-48fa-b1da-d6a90218e1dd.png)

### Steps To Reproduce

The error appeared after the update to v4.10.1, everything was working properly before

This only happens when going through the reverse proxy.

It works by connecting directly to the container ip http://xxx.xxx.x.x:8443

### Environment

```markdown
- OS: debian bullseye
- reverse proxy: nginx 1.18.0
- podman: v3.4.7
```

### CPU architecture

x86-64

### Docker creation

```bash
# Podman rootless container

podman run -dt --name vscode -v /etc/localtime:/etc/localtime:ro \
-v /data/1_hourly/homeassistant/config:/appdata/homeassistant \
-v /data/2_daily/appdaemon/config:/appdata/appdaemon \
-v /data/2_daily/esphome/config:/appdata/esphome \
-v /data/2_daily/mosquitto/config/mosquitto.conf:/appdata/mosquitto/mosquitto.conf \
-v /data/2_daily/zigbe2mqtt/data:/appdata/zigbee2mqtt \
-v /data/2_daily/zwavejs/config:/appdata/zwavejs
-v /data/3_weekly/vscode/config:/config \
--secret vscodepwd -e FILE__PASSWORD=/run/secrets/vscodepwd -e PUID=0 -e PGID=0 \
-p 8443:8443 linuxserver/code-server:latest
```

### Container logs

```bash
[custom-init] No custom files found, skipping...
[2023-03-07T22:04:15.960Z] info  code-server 4.10.1 d477972c68fc8c8e8d610aa7287db87ba90e55c7
[2023-03-07T22:04:15.961Z] info  Using user-data-dir ~/data
[2023-03-07T22:04:15.971Z] info  Using config file ~/.config/code-server/config.yaml
[2023-03-07T22:04:15.972Z] info  HTTP server listening on http://0.0.0.0:8443/
[2023-03-07T22:04:15.972Z] info    - Authentication is enabled
[2023-03-07T22:04:15.972Z] info      - Using password from $PASSWORD
[2023-03-07T22:04:15.972Z] info    - Not serving HTTPS
[ls.io-init] done.
[2023-03-07T22:04:16.753Z] error Forbidden HttpError: Forbidden
    at ensureOrigin (/app/code-server/out/node/http.js:288:15)
    at wrapped (/app/code-server/out/node/wsRouter.js:64:24)
    at Layer.handle [as handle_request] (/app/code-server/node_modules/router/lib/layer.js:102:15)
    at next (/app/code-server/node_modules/router/lib/route.js:144:13)
    at Route.dispatch (/app/code-server/node_modules/router/lib/route.js:109:3)
    at handle (/app/code-server/node_modules/router/index.js:515:11)
    at Layer.handle [as handle_request] (/app/code-server/node_modules/router/lib/layer.js:102:15)
    at /app/code-server/node_modules/router/index.js:291:22
    at param (/app/code-server/node_modules/router/index.js:368:14)
    at param (/app/code-server/node_modules/router/index.js:379:14)
[2023-03-07T22:04:16.774Z] error Forbidden HttpError: Forbidden
    at ensureOrigin (/app/code-server/out/node/http.js:288:15)
    at wrapped (/app/code-server/out/node/wsRouter.js:64:24)
    at Layer.handle [as handle_request] (/app/code-server/node_modules/router/lib/layer.js:102:15)
    at next (/app/code-server/node_modules/router/lib/route.js:144:13)
    at Route.dispatch (/app/code-server/node_modules/router/lib/route.js:109:3)
    at handle (/app/code-server/node_modules/router/index.js:515:11)
    at Layer.handle [as handle_request] (/app/code-server/node_modules/router/lib/layer.js:102:15)
    at /app/code-server/node_modules/router/index.js:291:22
    at param (/app/code-server/node_modules/router/index.js:368:14)
    at param (/app/code-server/node_modules/router/index.js:379:14)
[2023-03-07T22:04:16.793Z] error Forbidden HttpError: Forbidden
    at ensureOrigin (/app/code-server/out/node/http.js:288:15)
    at wrapped (/app/code-server/out/node/wsRouter.js:64:24)
    at Layer.handle [as handle_request] (/app/code-server/node_modules/router/lib/layer.js:102:15)
    at next (/app/code-server/node_modules/router/lib/route.js:144:13)
    at Route.dispatch (/app/code-server/node_modules/router/lib/route.js:109:3)
    at handle (/app/code-server/node_modules/router/index.js:515:11)
    at Layer.handle [as handle_request] (/app/code-server/node_modules/router/lib/layer.js:102:15)
    at /app/code-server/node_modules/router/index.js:291:22
    at param (/app/code-server/node_modules/router/index.js:368:14)
    at param (/app/code-server/node_modules/router/index.js:379:14)
[2023-03-07T22:04:16.811Z] error Forbidden HttpError: Forbidden
    at ensureOrigin (/app/code-server/out/node/http.js:288:15)
    at wrapped (/app/code-server/out/node/wsRouter.js:64:24)
    at Layer.handle [as handle_request] (/app/code-server/node_modules/router/lib/layer.js:102:15)
    at next (/app/code-server/node_modules/router/lib/route.js:144:13)
    at Route.dispatch (/app/code-server/node_modules/router/lib/route.js:109:3)
    at handle (/app/code-server/node_modules/router/index.js:515:11)
    at Layer.handle [as handle_request] (/app/code-server/node_modules/router/lib/layer.js:102:15)
    at /app/code-server/node_modules/router/index.js:291:22
    at param (/app/code-server/node_modules/router/index.js:368:14)
    at param (/app/code-server/node_modules/router/index.js:379:14)
```

**Comment by aptalca** [comment]
That's an issue with your reverse proxy. If you're using SWAG, update your confs to the latest. I had the same issue, and a conf update fixed it.

**Comment by Herbs851** [comment]
Hi @aptalca,

I don't use swag but a classic nginx installation on a lxc container.

But I will investigate this side, thanks.

**Comment by aptalca** [comment]
https://coder.com/docs/code-server/latest/guide#using-lets-encrypt-with-nginx

**Comment by Herbs851** [comment]
For information, it seems that these headers are no longer supported : 

```
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $scheme;
proxy_set_header X-Forwarded-Host $host:$server_port;
proxy_set_header X-Forwarded-Port $server_port;
```
without these it works correctly again with v4.10.1

**Comment by aptalca** [comment]
They are supported, but your incorrect header setting is breaking csrf
`X-Forwarded-Host $host:$server_port;` needs to be just `$host`, without the port, as there is a separate header for port

**Comment by Herbs851** [comment]
You are right.

I've had this header with this error for a long time and it hasn't been a problem.
I guess I was lucky ;)

Thank you very much !!!

**Comment by masterwishx** [comment]
I have same problem on oracle cloud + nginx proxy manager + Authentik.
I think I should add to Authentik to bypass some think?
