### ISSUE TITLE
[BUG] Turn on Cloud Changes Error

### ISSUE THREAD

**Issue by shubhankartrivedi** [linuxserver/docker-code-server#159]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

Turning on cloud changes gives no response.
Turning it on from settings gives this response:

`Unable to initialize sessions sync as session sync preference is not configured in product.json.`
<img width="534" alt="Screenshot 2023-09-30 at 5 38 33 PM" src="https://github.com/linuxserver/docker-code-server/assets/78972053/c644b280-4db1-46c1-9c53-ee0ed0c684c9">

### Expected Behavior

It should turn on and allow me to login.

### Steps To Reproduce

1. Install in CasaOS running on RPI4 with RpiOS 64

### Environment

```markdown
- OS: RpiOS 64 with CasaOS
- How docker service was installed: from CasaOS AppStore
```

### CPU architecture

arm64

### Docker creation

<img width="633" alt="Screenshot 2023-09-30 at 5 40 45 PM" src="https://github.com/linuxserver/docker-code-server/assets/78972053/a153d6d2-c66a-424b-b32c-f567a897e352">

### Container logs

```bash
vscode  | [migrations] started
vscode  | [migrations] no migrations found
vscode  | ───────────────────────────────────────
vscode  | 
vscode  | 
vscode  |       ██╗     ███████╗██╗ ██████╗ 
vscode  |       ██║     ██╔════╝██║██╔═══██╗
vscode  |       ██║     ███████╗██║██║   ██║
vscode  |       ██║     ╚════██║██║██║   ██║
vscode  |       ███████╗███████║██║╚██████╔╝
vscode  |       ╚══════╝╚══════╝╚═╝ ╚═════╝ 
vscode  | 
vscode  | 
vscode  |    Brought to you by linuxserver.io
vscode  | ───────────────────────────────────────
vscode  | 
vscode  | 
vscode  | To support LSIO projects visit:
vscode  | https://www.linuxserver.io/donate/
vscode  | 
vscode  | 
vscode  | ───────────────────────────────────────
vscode  | GID/UID
vscode  | ───────────────────────────────────────
vscode  | 
vscode  | 
vscode  | User UID:    1000
vscode  | User GID:    1000
vscode  | ───────────────────────────────────────
vscode  | 
vscode  | 
vscode  | setting up sudo access
vscode  | adding abc to sudoers
vscode  | setting sudo password using SUDO_PASSWORD env var
vscode  | New password: Retype new password: passwd: password updated successfully
vscode  | [custom-init] No custom files found, skipping...
vscode  | [2023-09-30T12:03:14.897Z] info  Wrote default config file to /config/.config/code-server/config.yaml
vscode  | [2023-09-30T12:03:16.217Z] info  code-server 4.17.1 2eba7af117ea58d45a6c6449ee4fe63c8d4d53aa
vscode  | [2023-09-30T12:03:16.221Z] info  Using user-data-dir /config/data
vscode  | [2023-09-30T12:03:16.271Z] info  Using config file /config/.config/code-server/config.yaml
vscode  | [2023-09-30T12:03:16.271Z] info  HTTP server listening on http://0.0.0.0:8443/
vscode  | [2023-09-30T12:03:16.272Z] info    - Authentication is enabled
vscode  | [2023-09-30T12:03:16.272Z] info      - Using password from $PASSWORD
vscode  | [2023-09-30T12:03:16.272Z] info    - Not serving HTTPS
vscode  | [2023-09-30T12:03:16.272Z] info  Session server listening on /config/data/code-server-ipc.sock
vscode  | [ls.io-init] done.
vscode  | [12:03:19] 
vscode  | 
vscode  | 
vscode  | 
vscode  | 
vscode  | 
vscode  | 
vscode  | 
vscode  | 
vscode  | [12:03:19] Extension host agent started.
vscode  | [12:03:19] Started initializing default profile extensions in extensions installation folder. file:///config/extensions
vscode  | [12:03:19] Completed initializing default profile extensions in extensions installation folder. file:///config/extensions
vscode  | File not found: /app/code-server/lib/vscode/out/vsda_bg.wasm
vscode  | File not found: /app/code-server/lib/vscode/out/vsda.js
vscode  | [12:03:22] [192.168.0.100][e018bbb7][ManagementConnection] New connection established.
vscode  | [12:03:25] [192.168.0.100][4826c9e2][ExtensionHostConnection] New connection established.
vscode  | [12:03:25] [192.168.0.100][4826c9e2][ExtensionHostConnection] <669> Launched Extension Host Process.
vscode  | [12:05:00] [192.168.0.100][e018bbb7][ManagementConnection] The client has disconnected gracefully, so the connection will be disposed.
vscode  | [12:05:00] Error: Throttler is disposed
vscode  |     at c.queue (/app/code-server/lib/vscode/out/vs/server/node/server.main.js:67:13689)
vscode  |     at /app/code-server/lib/vscode/out/vs/server/node/server.main.js:67:15275
vscode  |     at /app/code-server/lib/vscode/out/vs/server/node/server.main.js:67:14911
vscode  |     at runNextTicks (node:internal/process/task_queues:60:5)
vscode  |     at listOnTimeout (node:internal/timers:538:9)
vscode  |     at process.processTimers (node:internal/timers:512:7)
vscode  | [12:05:00] Error: Throttler is disposed
vscode  |     at c.queue (/app/code-server/lib/vscode/out/vs/server/node/server.main.js:67:13689)
vscode  |     at /app/code-server/lib/vscode/out/vs/server/node/server.main.js:67:15275
vscode  |     at /app/code-server/lib/vscode/out/vs/server/node/server.main.js:67:14911
vscode  |     at runNextTicks (node:internal/process/task_queues:60:5)
vscode  |     at listOnTimeout (node:internal/timers:538:9)
vscode  |     at process.processTimers (node:internal/timers:512:7)
vscode  | [12:05:00] Error: Throttler is disposed
vscode  |     at c.queue (/app/code-server/lib/vscode/out/vs/server/node/server.main.js:67:13689)
vscode  |     at /app/code-server/lib/vscode/out/vs/server/node/server.main.js:67:15275
vscode  |     at /app/code-server/lib/vscode/out/vs/server/node/server.main.js:67:14911
vscode  |     at runNextTicks (node:internal/process/task_queues:60:5)
vscode  |     at listOnTimeout (node:internal/timers:538:9)
vscode  |     at process.processTimers (node:internal/timers:512:7)
vscode  | [12:05:00] Error: Throttler is disposed
vscode  |     at c.queue (/app/code-server/lib/vscode/out/vs/server/node/server.main.js:67:13689)
vscode  |     at /app/code-server/lib/vscode/out/vs/server/node/server.main.js:67:15275
vscode  |     at /app/code-server/lib/vscode/out/vs/server/node/server.main.js:67:14911
vscode  |     at runNextTicks (node:internal/process/task_queues:60:5)
vscode  |     at listOnTimeout (node:internal/timers:538:9)
vscode  |     at process.processTimers (node:internal/timers:512:7)
vscode  | [12:05:00] Error: Throttler is disposed
vscode  |     at c.queue (/app/code-server/lib/vscode/out/vs/server/node/server.main.js:67:13689)
vscode  |     at /app/code-server/lib/vscode/out/vs/server/node/server.main.js:67:15275
vscode  |     at /app/code-server/lib/vscode/out/vs/server/node/server.main.js:67:14911
vscode  |     at runNextTicks (node:internal/process/task_queues:60:5)
vscode  |     at listOnTimeout (node:internal/timers:538:9)
vscode  |     at process.processTimers (node:internal/timers:512:7)
vscode  | [12:05:00] Error: Throttler is disposed
vscode  |     at c.queue (/app/code-server/lib/vscode/out/vs/server/node/server.main.js:67:13689)
vscode  |     at /app/code-server/lib/vscode/out/vs/server/node/server.main.js:67:15275
vscode  |     at /app/code-server/lib/vscode/out/vs/server/node/server.main.js:67:14911
vscode  |     at runNextTicks (node:internal/process/task_queues:60:5)
vscode  |     at listOnTimeout (node:internal/timers:538:9)
vscode  |     at process.processTimers (node:internal/timers:512:7)
vscode  | [12:05:00] Error: Throttler is disposed
vscode  |     at c.queue (/app/code-server/lib/vscode/out/vs/server/node/server.main.js:67:13689)
vscode  |     at /app/code-server/lib/vscode/out/vs/server/node/server.main.js:67:15275
vscode  |     at /app/code-server/lib/vscode/out/vs/server/node/server.main.js:67:14911
vscode  |     at runNextTicks (node:internal/process/task_queues:60:5)
vscode  |     at listOnTimeout (node:internal/timers:538:9)
vscode  |     at process.processTimers (node:internal/timers:512:7)
vscode  | [12:05:00] Error: Throttler is disposed
vscode  |     at c.queue (/app/code-server/lib/vscode/out/vs/server/node/server.main.js:67:13689)
vscode  |     at /app/code-server/lib/vscode/out/vs/server/node/server.main.js:67:15275
vscode  |     at /app/code-server/lib/vscode/out/vs/server/node/server.main.js:67:14911
vscode  |     at runNextTicks (node:internal/process/task_queues:60:5)
vscode  |     at listOnTimeout (node:internal/timers:538:9)
vscode  |     at process.processTimers (node:internal/timers:512:7)
vscode  | [12:05:00] Error: Throttler is disposed
vscode  |     at c.queue (/app/code-server/lib/vscode/out/vs/server/node/server.main.js:67:13689)
vscode  |     at /app/code-server/lib/vscode/out/vs/server/node/server.main.js:67:15275
vscode  |     at /app/code-server/lib/vscode/out/vs/server/node/server.main.js:67:14911
vscode  |     at runNextTicks (node:internal/process/task_queues:60:5)
vscode  |     at listOnTimeout (node:internal/timers:538:9)
vscode  |     at process.processTimers (node:internal/timers:512:7)
vscode  | [12:05:00] Error: Throttler is disposed
vscode  |     at c.queue (/app/code-server/lib/vscode/out/vs/server/node/server.main.js:67:13689)
vscode  |     at /app/code-server/lib/vscode/out/vs/server/node/server.main.js:67:15275
vscode  |     at /app/code-server/lib/vscode/out/vs/server/node/server.main.js:67:14911
vscode  |     at runNextTicks (node:internal/process/task_queues:60:5)
vscode  |     at listOnTimeout (node:internal/timers:538:9)
vscode  |     at process.processTimers (node:internal/timers:512:7)
vscode  | [12:05:00] Error: Throttler is disposed
vscode  |     at c.queue (/app/code-server/lib/vscode/out/vs/server/node/server.main.js:67:13689)
vscode  |     at /app/code-server/lib/vscode/out/vs/server/node/server.main.js:67:15275
vscode  |     at /app/code-server/lib/vscode/out/vs/server/node/server.main.js:67:14911
vscode  |     at runNextTicks (node:internal/process/task_queues:60:5)
vscode  |     at listOnTimeout (node:internal/timers:538:9)
vscode  |     at process.processTimers (node:internal/timers:512:7)
vscode  | [12:05:05] [192.168.0.100][4826c9e2][ExtensionHostConnection] <669> Extension Host Process exited with code: 0, signal: null.
vscode  | File not found: /app/code-server/lib/vscode/out/vsda_bg.wasm
vscode  | File not found: /app/code-server/lib/vscode/out/vsda.js
vscode  | [12:07:12] [192.168.0.100][e75e43e1][ManagementConnection] New connection established.
vscode  | [12:07:15] [192.168.0.100][9d73e1ec][ExtensionHostConnection] New connection established.
vscode  | [12:07:15] [192.168.0.100][9d73e1ec][ExtensionHostConnection] <2029> Launched Extension Host Process.
```

**Comment by Roxedus** [comment]
That's a feature only available to Microsoft builds of the codebase, which this is not.

**Comment by Roxedus** [comment]
Microsoft has since changed how the plugin works, it does not need the Microsoft propitiatory blobs anymore.
Copilot has worked for months.

The application bundled is listed in the readme, as with any other of our containers.

**Comment by acondura** [comment]
Well, I can find it in the marketplace https://marketplace.visualstudio.com/items?itemName=GitHub.copilot but when I search for Copilot in the Extensions tab, it does not bring it up so that I can install it.

**Comment by acondura** [comment]
This is the list I get https://open-vsx.org/?search=Copilot&sortBy=relevance&sortOrder=desc
