### ISSUE TITLE
Running code-server --install-extension fails with `error vscode Error: Server returned 500`

### ISSUE THREAD

**Issue by ifduyue** [linuxserver/docker-code-server#46]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

Install extension without error. 
This works in ghcr.io/linuxserver/code-server:version-v3.6.2, but not in version-v3.7.4 (latest)

## Current Behavior

```bash
root@62c6e6d23349:/# curl -Lso /tmp/ms-python.vsix https://open-vsx.org/api/ms-python/python/2020.10.332292344/file/ms-python.python-2020.10.332292344.vsix
root@62c6e6d23349:/# s6-setuidgid abc code-server --user-data-dir /config/data --extensions-dir /config/extensions --disable-telemetry --install-extension /tmp/ms-python.vsix 
Installing extensions...
Extension 'ms-python.vsix' was successfully installed.
[2020-12-09T11:26:59.795Z] error vscode Server returned 500
[2020-12-09T11:26:59.798Z] error vscode Error: Server returned 500
    at Object.t.asJson (/usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/server/entry.js:373:933)
    at j.queryGallery (/usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/server/entry.js:393:695)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async j.query (/usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/server/entry.js:392:642)
    at async j.getExtensions (/usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/server/entry.js:390:251)
    at async /usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/server/entry.js:541:148
    at async Promise.all (index 0)
    at async J.getGalleryExtensions (/usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/server/entry.js:541:117)
    at async Promise.all (index 0)
    at async J.installExtensions (/usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/server/entry.js:540:13)
    at async J.run (/usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/server/entry.js:538:205)
    at async /usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/server/entry.js:545:678
    at async process.<anonymous> (/usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/server/entry.js:553:669)
```

## Steps to Reproduce

1.  `docker run -d   --name=code-server   -e PUID=1000   -e PGID=1000   -e TZ=Europe/London   -e PASSWORD=password  -e SUDO_PASSWORD=password  -e PROXY_DOMAIN=code-server.my.domain   -p 8443:8443   --restart unless-stopped   ghcr.io/linuxserver/code-server`
2. `docker exec -ti  code-server /bin/bash` and then `curl -Lso /tmp/ms-python.vsix https://open-vsx.org/api/ms-python/python/2020.10.332292344/file/ms-python.python-2020.10.332292344.vsix && s6-setuidgid abc code-server --user-data-dir /config/data --extensions-dir /config/extensions --disable-telemetry --install-extension /tmp/ms-python.vsix`

## Environment
**OS:** opensuse-tumbleweed VERSION_ID="20201207"
**CPU architecture:** x86_64
**How docker service was installed:** zypper install docker

## Command used to create docker container (run/create/compose/screenshot)

`docker run -d   --name=code-server   -e PUID=1000   -e PGID=1000   -e TZ=Europe/London   -e PASSWORD=password  -e SUDO_PASSWORD=password  -e PROXY_DOMAIN=code-server.my.domain   -p 8443:8443   --restart unless-stopped   ghcr.io/linuxserver/code-server`

```bash
# docker images  | grep ghcr
ghcr.io/linuxserver/code-server   latest              22eeb275bad0        7 days ago          551MB
```

## Docker logs

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing... 
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing... 

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \ 
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing... 
setting up sudo access
adding abc to sudoers
setting sudo password
Enter new UNIX password: Retype new UNIX password: passwd: password updated successfully
[cont-init.d] 30-config: exited 0.
[cont-init.d] 99-custom-scripts: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[2020-12-09T11:18:07.110Z] info  Wrote default config file to ~/.config/code-server/config.yaml
[2020-12-09T11:18:07.328Z] info  code-server 3.7.4 11f53784c58f68e7f4c5b3b8dae9407caa41725b
[2020-12-09T11:18:07.329Z] info  Using user-data-dir ~/data
[2020-12-09T11:18:07.337Z] info  Using config file ~/.config/code-server/config.yaml
[2020-12-09T11:18:07.337Z] info  HTTP server listening on http://0.0.0.0:8443 
[2020-12-09T11:18:07.337Z] info    - Authentication is enabled
[2020-12-09T11:18:07.337Z] info      - Using password from $PASSWORD
[2020-12-09T11:18:07.337Z] info    - Not serving HTTPS
[2020-12-09T11:18:07.337Z] info    - Proxying the following domain:
[2020-12-09T11:18:07.337Z] info      - *.code-server.my.domain
```

**Comment by ifduyue** [comment]
On a second thought this is more related to code-server, but I've already opened this issue. Sorry if I have bothered anyone.
