### ISSUE TITLE
Cannot install extensions

### ISSUE THREAD

**Issue by krlf** [linuxserver/docker-code-server#69]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Steps to Reproduce

1. Run the server
2. Open VS Code in browser and try to install any extension
3. See the error:
```
2021-05-31 17:43:08.194] [window] [error] ["downloading: getaddrinfo EAI_AGAIN storage.googleapis.com","    at x.downloadInstallableExtension (/usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/server/entry.js:36:67534)","    at processTicksAndRejections (internal/process/task_queues.js:97:5)"]
[2021-05-31 17:43:08.216] [window] [error] getaddrinfo EAI_AGAIN storage.googleapis.com: downloading: getaddrinfo EAI_AGAIN storage.googleapis.com
    at x.downloadInstallableExtension (/usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/server/entry.js:36:67534)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

## Environment
**OS:** Linux
**CPU architecture:** arm32
**How docker service was installed:** nas OS provided

## Command used to create docker container (run/create/compose/screenshot)
docker run -d --name=code-server -e PUID=1002 -e PGID=100 -e TZ=Europe/Moscow -e PROXY_DOMAIN=hc2.lan -p 8443:8443 -e SUDO_PASSWORD=123 -v /sharedfolders/syncthing/syncDir/projects/Projects:/Projects -v /sharedfolders/syncthing/syncDir/projects/Projects/config:/config --restart unless-stopped ghcr.io/linuxserver/code-server

## Docker Logs

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing...
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing...
usermod: no changes

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1002
User gid:    100
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing...
setting up sudo access
setting sudo password using SUDO_PASSWORD env var
Enter new UNIX password: Retype new UNIX password: passwd: password updated successfully
[cont-init.d] 30-config: exited 0.
[cont-init.d] 99-custom-scripts: executing...
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
starting with no password
[2021-05-31T19:58:10.726Z] info  code-server 3.10.2 387b12ef4ca404ffd39d84834e1f0776e9e3c005
[2021-05-31T19:58:10.730Z] info  Using user-data-dir ~/data
[2021-05-31T19:58:10.804Z] info  Using config file ~/.config/code-server/config.yaml
[2021-05-31T19:58:10.805Z] info  HTTP server listening on http://0.0.0.0:8443
[2021-05-31T19:58:10.805Z] info    - Authentication is disabled
[2021-05-31T19:58:10.805Z] info    - Not serving HTTPS
[2021-05-31T19:58:10.805Z] info    - Proxying the following domain:
[2021-05-31T19:58:10.806Z] info      - *.hc2.lan
```

## Supposed issue
The only root can resolve hosnames because of strict rights on resolve.conf
```
root@a956d6eb28b3:/# ls -la /etc/resolv.conf
-rw-r-----+ 1 root root 19 May 31 22:01 /etc/resolv.conf
```
Appling of
```
chmod a+r /etc/resolv.conf
```
solves the problem.

Not sure this issue should be fixed in scope of linuxserver. Sorry if not.

**Comment by Roxedus** [comment]
Please provide full container logs, as the template wanted.

**Comment by krlf** [comment]
Docker log was added but not sure it useful.

**Comment by aptalca** [comment]
We don't touch `/etc/resolv.conf` as it's handled by the docker service. It looks to be an issue with you nas provider. We only support the official docker repo for installing docker

**Comment by krlf** [comment]
I see. It should be bind-mounted from the host. On the host i have the following:
```
root@hc2:~# ls -la /etc/resolv.conf
lrwxrwxrwx 1 root root 31 Aug  1  2019 /etc/resolv.conf -> /etc/resolvconf/run/resolv.conf
root@hc2:~# ls -la /etc/resolvconf/run/resolv.conf
-rw-r--r-- 1 root root 19 Apr 19 19:33 /etc/resolvconf/run/resolv.conf
```
Ok then. I will change permissions manually if needed.
Thanks.

**Comment by krlf** [comment]
N/A
