### ISSUE TITLE
Terminal does not open

### ISSUE THREAD

**Issue by FabianTe** [linuxserver/docker-code-server#93]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
I can open a terminal in the browser.

## Current Behavior
The terminal opens for about half a second and then closes.
While it is open it shows "This account is currently not available"

## Steps to Reproduce

Define service like this:

```yml
code:
  image: linuxserver/code-server:3.12.0
    environment:
      PUID: 33 # www-data
      PGID: 33 # www-data
      PROXY_DOMAIN: code.docker.localhost #optional
    ports:
      - 80:8443 # I have a reverse proxy in front of this container.
```

Then start the service and try to 

## Environment
**OS:** Current Ubuntu LTS
**CPU architecture:** x86_64
**How docker service was installed:** long time ago. Pretty much standard like documented by Docker

## Docker logs

```log
code_1      | [2021-12-15T10:46:41.192Z] info  HTTP server listening on http://0.0.0.0:8443 
code_1      | [2021-12-15T10:46:41.192Z] info    - Authentication is disabled 
code_1      | [2021-12-15T10:46:41.192Z] info    - Not serving HTTPS 
code_1      | [2021-12-15T10:46:41.192Z] info    - Proxying the following domain:
code_1      | [2021-12-15T10:46:41.192Z] info      - *.code.docker.localhost
code_1      | [2021-12-15T10:46:45.778Z] error vscode is not running Error: vscode is not running
code_1      |     at VscodeProvider.send (/usr/local/share/.config/yarn/global/node_modules/code-server/out/node/vscode.js:121:19)
code_1      |     at VscodeProvider.sendWebsocket (/usr/local/share/.config/yarn/global/node_modules/code-server/out/node/vscode.js:117:14)
code_1      |     at async /usr/local/share/.config/yarn/global/node_modules/code-server/out/node/routes/vscode.js:205:5
code_1      | [2021-12-15T10:46:45.781Z] error vscode is not running Error: vscode is not running
code_1      |     at VscodeProvider.send (/usr/local/share/.config/yarn/global/node_modules/code-server/out/node/vscode.js:121:19)
code_1      |     at VscodeProvider.sendWebsocket (/usr/local/share/.config/yarn/global/node_modules/code-server/out/node/vscode.js:117:14)
code_1      |     at async /usr/local/share/.config/yarn/global/node_modules/code-server/out/node/routes/vscode.js:205:5
code_1      | [2021-12-15T10:46:46.122Z] error vscode is not running Error: vscode is not running
code_1      |     at VscodeProvider.send (/usr/local/share/.config/yarn/global/node_modules/code-server/out/node/vscode.js:121:19)
code_1      |     at VscodeProvider.sendWebsocket (/usr/local/share/.config/yarn/global/node_modules/code-server/out/node/vscode.js:117:14)
code_1      |     at async /usr/local/share/.config/yarn/global/node_modules/code-server/out/node/routes/vscode.js:205:5
code_1      | [2021-12-15T10:46:46.135Z] error vscode is not running Error: vscode is not running
code_1      |     at VscodeProvider.send (/usr/local/share/.config/yarn/global/node_modules/code-server/out/node/vscode.js:121:19)
code_1      |     at VscodeProvider.sendWebsocket (/usr/local/share/.config/yarn/global/node_modules/code-server/out/node/vscode.js:117:14)
code_1      |     at async /usr/local/share/.config/yarn/global/node_modules/code-server/out/node/routes/vscode.js:205:5
code_1      | [main 2021-12-15T10:46:48.494Z] getUnixShellEnvironment#error Failed to get environment (code 1, signal null)
```

**Comment by Roxedus** [comment]
This happens because you are using a user that has no shell in the container, www-data. We recommend using a user account rather than one of the common IDs and names.

**Comment by FabianTe** [comment]
Hi, thanks for your reply. 

I see, instead of using `33` as user and group id, using `www-data` should be fine, right?

In my scenario I want to use code-server to allow editing files hosted by an apache webserver. Therefore I want to ensure that created / edited files are always owned by www-data.

**Comment by FabianTe** [comment]
Update: I tried using www-data but then my user is `abc`. What am I missing? Thanks for your help :)

**Comment by j0nnymoe** [comment]
You need to use a normal user account.

**Comment by FabianTe** [comment]
In other words: Using www-data as user / group is not an option because it is a system account, right? (I am not that confident with linux user management)

**Comment by Roxedus** [comment]
Yes

**Comment by FabianTe** [comment]
Alright, thanks for your feedback!
